repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        exclude: docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      #    - id: double-quote-string-fixer
      #    - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: name-tests-test
      #      - id: pretty-format-json
      - id: sort-simple-yaml
      - id: mixed-line-ending
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
      - id: trailing-whitespace
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types_or: [python, pyi]
      - id: isort
        name: isort
        entry: isort
        args: [--profile=black]
        language: python
      - id: docformatter
        name: docformatter
        entry: docformatter
        language: python
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: python
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        args:
          - --expand-star-imports
          - --ignore-init-module-imports
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
      - id: pycln
        name: pycln
        entry: pycln
        language: python
        args: [--config=setup.cfg]
